TRAIN:
  ENABLE: True
  DATASET: ucf101
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [128, 160]
  TRAIN_CROP_SIZE: 112
  TEST_CROP_SIZE: 128
  INPUT_CHANNEL_NUM: [3]
MGMA:
  TYPE: NONE
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 100
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 30, 40, 50]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 10.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 101
  ARCH: r3d
  DEPTH: 34
  MODEL_NAME: MGMANet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: True
  DATASET: ucf101
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: True
